### ISSUE TITLE
@Jenifer-xm 如果使用的是本仓库自带的数据集，只需要修改路径就可以运行，这已经过多人测试。如果使用的是您本人的数据集，请根据实际情况修改。

### ISSUE THREAD

**Issue by Jenifer-xm** [FlyuZ/voxelmorph-tf2-min#3]
@Jenifer-xm 如果使用的是本仓库自带的数据集，只需要修改路径就可以运行，这已经过多人测试。如果使用的是您本人的数据集，请根据实际情况修改。

_Originally posted by @FlyuZ in https://github.com/FlyuZ/voxelmorph-tf2-min/issues/2#issuecomment-559386796_

**Comment by Jenifer-xm** [comment]
报错情况是这样的，我用自己的数据如果修改大小和你GitHub上的一样的话是没有问题的，维度改变了就报错
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/38251541/69789555-c05ceb80-11fb-11ea-8967-f827342b94fa.png">

**Comment by FlyuZ** [comment]
@Jenifer-xm 请修改ndims，以及卷积层的维数，其他地方需要您自己检查一下了，我测试过2维和3维数据，都是可以的

**Comment by Jenifer-xm** [comment]
可以加下您的微信吗，这个voxelmorph后边有问题方便问您，
我的微信是w1239978244，谢谢啦
