### ISSUE TITLE
SomeQuestion

### ISSUE THREAD

**Issue by klfxmu** [FlyuZ/voxelmorph-tf2-min#4]
Hello:
         Does your code refer to VoxelMorph?or just refer to other?
         I have a question:why can you train your network with only two graphs and get good results?
Waiting your answer.
Thanks!

**Comment by FlyuZ** [comment]
Only refer to VoxelMorph, please see the paper for specific effect explanation

**Comment by klfxmu** [comment]
您好！打扰您一下：
        感谢您的回复，请问您的代码对比voxelmorph原代码删减了哪些功能呢？
       我看您推荐的作者官方教程，2d和3d配准代码也是分开的，您的代码既可以使用3d也可以2d吗？
      请问如果要复现voxelmorph的代码该怎么去训练呢，无监督的训练我该用什么样的数据呢！因为官方代码并没有提供h5model。
      能力实在有限还是无法理解为什么您的代码用两张图片就能训练并得到较好的结果。

希望您能回复，谢谢您的帮助，万分感谢您




On 02/22/2021 12:43, Feifei wrote:

Only refer to VoxelMorph, please see the paper for specific effect explanation

**Comment by FlyuZ** [comment]
。
