### ISSUE TITLE
Back propagation of transform layer? 

### ISSUE THREAD

**Issue by XXZhou25** [FlyuZ/voxelmorph-tf2-min#5]
Hi, I was wondering how you implement back propagation of the transform layer for dense field transform? I tried to reproduce VoxelMorph's work but stuck on the backpropagation part. 

I will appreciate if you could share some ideas.
Thanks!

**Comment by FlyuZ** [comment]
I haven't reproduced it. Most of the code is the same as the original. good luck.

**Comment by XXZhou25** [comment]
> I haven't reproduced it. Most of the code is the same as the original. good luck.

Actually I was thinking if we define a new layer, we probably have to define the back propagation rule right? Probably you didn't reproduce VoxelMorph's DNN model framework, but I saw you also define the densetransformation layer.
So in this case, I was wondering how you define propagation for that layer?

**Comment by FlyuZ** [comment]
sorry, i can't help you.

**Comment by XXZhou25** [comment]
> sorry, i can't help you.

 I am not looking for an answer. I was expecting to have a discussion if you have some idea about this since you are implementing that part, so I assume you probably know more than me. This is what github issue for. But never mind. Thanks anyway.
